### ISSUE TITLE
Data discrepencies

### ISSUE THREAD

**Issue by magtro** [rOpenGov/fmi2#13]
Hi!

First of all I would like to say thank you for providing an excellent alternative of fetching Finnish Meteorological Data through your fmi2 R package.

I have noticed some discrepancies when I compare the data I can manually download from https://en.ilmatieteenlaitos.fi/ using their graphical user-friendly web API (i.e choosing a station and parameter to produce a .csv file).

For example, one can compare Hammarlands Märkets (id: 100919) 2018-01-01 00:00.  We see that the values for WD_PT1H_AVG  = 141, and WS_PT1H_AVG = 11.4. However, using https://en.ilmatieteenlaitos.fi/download-observations for the parameters "wind speed" and "wind direction", the values for that same time is  Wind direction (deg) = 145, Wind speed (m/s) = 10.7.

Do you know what the reason is behind such discrepancies?

Regards,
Magnus Tronstad

**Comment by jlehtoma** [comment]
Thanks for reporting this @magtro , will have a closer look as soon as possible.

**Comment by jlehtoma** [comment]
Finally got around looking at this. Using following query

```
test_data <- fmi2::obs_weather_hourly(starttime = "2018-01-01",
                                      endtime = "2018-01-02",
                                      fmisid = 100919)

# Move geometry to get just a tibble
test_data$geometry <- NULL

# Get only wind speed and direction
sbst_data <- test_data %>%
  dplyr::filter(variable %in% c("WS_PT1H_AVG", "WD_PT1H_AVG")) %>%
  tidyr::pivot_wider(names_from = variable) %>%
  dplyr::rename(`Wind direction` = WD_PT1H_AVG,
                `Wind speed` = WS_PT1H_AVG) %>%
  dplyr::select(time, `Wind direction`, `Wind speed`)
```
 
returns a tibble that can be compared against [the manual data download service](https://cdn.fmi.fi/fmiodata-convert-api/preview/990829c9-69dc-487b-a6f6-79671d3d9d7d/?locale=en) linked by @magtro. Quick look reveals that *all* values are off. Discrepancies exist in [the data returned by the WFS](https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::observations::weather::hourly::simple&fmisid=100919&starttime=2018-01-01&endtime=2018-01-02) and don't seem to be caused by `fmi2`. Not sure what is causing the discrepancies and will have to contact the FMI.

**Comment by jlehtoma** [comment]
I submitted a question to the FMI open data helpdesk, which will be on a summer vacation until 13th August. Let's see if they have an idea once they get back.

**Comment by magtro** [comment]
Interesting,  thats for the update!

**Comment by jlehtoma** [comment]
I got a response from FMI open data helpdesk and the reason for the data discrepancies is that the API returns an average over a given hour whereas the data download service returns the exact value for a given time. So effectively they are different variables.
